<?php

namespace Database\Seeders;

use App\Models\User;
use Filament\Facades\Filament;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Database\Seeders\ProfilePerusahaanSeeder;
use Database\Seeders\KaryawanSeeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $guardName = Filament::getDefaultPanel()?->getAuthGuard() ?? config('auth.defaults.guard', 'web');
        $superAdminRoleName = config('filament-shield.super_admin.name', 'Super Admin');

        $superAdminRole = Role::firstOrCreate([
            'name' => $superAdminRoleName,
            'guard_name' => $guardName,
        ]);

        // Ensure super admin keeps every permission generated by Shield.
        $superAdminRole->syncPermissions(
            Permission::whereGuardName($guardName)->pluck('name')
        );

        $admin = User::firstOrCreate(
            ['email' => 'admin@example.com'],
            ['name' => 'Administrator', 'password' => Hash::make('password')]
        );
        $admin->assignRole($superAdminRole);

        $this->call([
            ProfilePerusahaanSeeder::class,
            KaryawanSeeder::class,
        ]);
    }
}
